[package]
name = "context-switch"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["services/google-transcribe"]

[dependencies]

[dev-dependencies]
# audio input
cpal = "0.15.3"
# audio output
rodio = "0.20.1"
