[package]
name = "context-switch"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ 
    "audio-knife", 
    "core",
    "endpoints/azure",
    "endpoints/google-transcribe", 
    "endpoints/openai-dialog", 
]

[dependencies]
context-switch-core = { workspace = true }
cs-azure = { workspace = true }

azure-speech = { workspace = true }

serde = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
tracing = {workspace = true }

# todo: is this needed?
uuid = "1.11.0"
serde_json = "1.0.133"
futures = "0.3.31"
derive_more = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
context-switch-core = { workspace = true }

dotenvy = { workspace = true }

# audio input
cpal = "0.15.3"
# audio output
rodio = "0.20.1"

cs-azure = { workspace = true }
google-transcribe = { path = "endpoints/google-transcribe" }
openai-dialog = { path = "endpoints/openai-dialog" }

tokio = { workspace = true, features = ["rt-multi-thread"] }

[workspace.dependencies]
tracing-subscriber = { version = "0.3.19" }

context-switch-core = { path = "core" }
cs-azure = { path = "endpoints/azure" }

anyhow = "1.0.93"
derive_more = { version = "1.0.0", features = ["full"] }
async-stream = { version = "0.3.6" }
tokio = { version = "1.41.1", features = ["sync"] }
futures = "0.3.31"
serde = "1.0.215"
serde_json = "1.0.133"
base64 = "0.22.1"
async-fn-stream = "0.2.2"
async-trait = "0.1.83"
tracing = "0.1.41"
dotenvy = { version = "0.15.7" }
url = { version = "2.5.4" }

# external dependencies.

azure-speech = { path = "external/azure-speech-sdk-rs" }
# openai-api-rs = "5.2.3"
openai-api-rs = { path = "external/openai-api-rs" }
