[package]
name = "context-switch"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["services/google-transcribe"]

[dependencies]

[dev-dependencies]
# audio input
cpal = "0.15.3"
# audio output
rodio = "0.20.1"
google-transcribe = { path = "services/google-transcribe" }
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }

[workspace.dependencies]
tokio = { version = "1.41.1", features = ["sync"] }
