[package]
name = "context-switch"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "audio-knife", 
    "core",
    "endpoints/azure-transcribe",
    "endpoints/google-transcribe", "endpoints/openai-dialog"]

[dependencies]
context-switch-core = { workspace = true }
azure-transcribe = { workspace = true }

azure-speech = { workspace = true }

serde = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
tracing = {workspace = true }

# todo: is this needed?
uuid = "1.11.0"
serde_json = "1.0.133"
futures = "0.3.31"
derive_more = { version = "1.0.0", features = ["full"] }

[dev-dependencies]
context-switch-core = { workspace = true }

dotenvy = { workspace = true }

# audio input
cpal = "0.15.3"
# audio output
rodio = "0.20.1"

azure-transcribe = { workspace = true }
google-transcribe = { path = "endpoints/google-transcribe" }
openai-dialog = { path = "endpoints/openai-dialog" }

tokio = { workspace = true, features = ["rt-multi-thread"] }

[workspace.dependencies]
context-switch-core = { path = "core" }
azure-transcribe = { path = "endpoints/azure-transcribe" }
azure-speech = "0.4.0"

anyhow = "1.0.93"
async-stream = { version = "0.3.6" }
tokio = { version = "1.41.1", features = ["sync"] }
futures = "0.3.31"
serde = "1.0.215"
serde_json = "1.0.133"
base64 = "0.22.1"
async-fn-stream = "0.2.2"
async-trait = "0.1.83"
tracing = "0.1.41"
dotenvy = { version = "0.15.7" }

