[package]
name = "context-switch"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "core", "services/azure-transcribe","services/google-transcribe"]

[dependencies]
anyhow = "1.0.93"
uuid = "1.11.0"
serde_json = "1.0.133"
futures = "0.3.31"

[dev-dependencies]
# audio input
cpal = "0.15.3"
# audio output
rodio = "0.20.1"
google-transcribe = { path = "services/google-transcribe" }
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
anyhow = "1.0.93"
context-switch-core = { workspace = true }

[workspace.dependencies]
context-switch-core = { path = "core" }

anyhow = "1.0.93"
async-stream = { version = "0.3.6" }
tokio = { version = "1.41.1", features = ["sync"] }
futures = "0.3.31"

