[package]
name = "audio-knife"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
anyhow = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
context-switch = { path = ".." }

axum = { version = "0.7.9", features = ["ws"] }

tracing-subscriber = { version = "0.3.19" }
futures-util = { version = "0.3.31" }