[package]
name = "azure-transcribe"
version = "0.1.0"
edition = "2021"

[dependencies]
azure-speech = "0.4.0"
hound = "3.5.1"

anyhow = { workspace = true }
futures = { workspace = true }
context-switch-core = { workspace = true }
async-stream = { workspace = true }
